### ISSUE TITLE
Descrição para categorias [asked  by Carol]

### ISSUE THREAD

**Issue by nataliarsand** [engageis/festivaldeideias#10]
Inserir texto nas páginas de cada categoria (navegação por categoria).

Para entender melhor sobre o tema Mobilidade Urbana, clique aqui (link para a pg fixa de temas)
                                                    Catástrofes Naturais
                                                    Violência
                                                     etc

**Comment by luizfonseca** [comment]
Fixed, see 2c8b53d29bccd3f1f942c68a8304c9126578d625
