### ISSUE TITLE
Integração com Mapas de Vista

### ISSUE THREAD

**Issue by BrenoCastroAlves** [engageis/festivaldeideias#13]
proposta de construção de um mapa com as ideias do festival.

A dificuldade aqui é integrar a plataforma do festival com Mapas de Vista ( https://github.com/hacklabr/mapasdevista ) , ferramenta de mapeamento baseada em wordpress, que será usada para construção deste mapa.

a proposta é construir um mapa com os dados da plataforma do festival, cruzando os bancos de dados para que não seja necessário incluir manualmente todos os pontos no mapa. Da mesma forma, precisamos que as atualizações realizadas na plataforma do festival sejam automaticamente atualizadas no site do mapeamento, para poupar esse trabalho impossível de manutenção.

aí está.

**Comment by luizfonseca** [comment]
Como estão pensando em alimentar a base de vocês? Pensei em uma api REST que devolva os dados de cada ideia.
Terei que verificar quanto código eu terei que adicionar pra essa funcionalidade, mas não demorará muito.

**Comment by BrenoCastroAlves** [comment]
Mano, eu realmente não sei como te ajudar. Eu só saberia alimentar a base
manualmente, que é exatamente o jeito que não pode ser. Estou tentando
colaboração de programadores, mas por enquanto ainda não consegui.

Mas uma coisa que eu já posso fazer é ir montando o site, subindo os
ícones, criando um primeiro protótipo com posts inseridos manualmente.

Pra isso, precisaria instalar wordpress no servidor de vocês e criar o
festivaldeideias.org.br/mapa. Consegue adiantar também essa?

Valeu Luiz, tamos aí.

com abraço,

2012/5/25 Luiz Fonseca <
reply@reply.github.com

**Comment by luizfonseca** [comment]
Bem, a API resolveria boa parte desses problemas. Infelizmente, não é possível instalar wordpress no servidor, usamos o Heroku (http://heroku.com).

No caso da API, imagine a seguinte situação: 
`GET /ideias/1`

E o output dessa request provavelmente retornaria um JSON com os dados da ideia em questão ou de todas (fica a critério no que você precisa que ele retorne)

```
{
 id: 1,
 titulo: "Titulo da ideia",
 texto_html: "Texto da ideia em formato HTML",
 localidade: "Aqui talvez iria a localidade de cada ideia, por cidade ou lat./long.",
}
```

E assim por diante. Caberia a você "puxar" esses dados e inclusive até dispensando o uso de banco de dados pra isso.
O que você acha?

**Comment by BrenoCastroAlves** [comment]
Luiz meu caro, olá,

compartilhei sua questão com os programadores que conheço e mexem com mapas
de vista, mas por enquanto ainda não tive resposta..

Eu, infelizmente, não vejo mais como avançar isso.. é o problema da
colaboração, ficamos reféns da boa vontade de terceiro para avançar coisas
legais..

se eu puder te ajudar com algum trabalho braçal, me dê o toque!

comabraço,

2012/5/31 Luiz Fonseca <
reply@reply.github.com

**Comment by luizfonseca** [comment]
Breno, não entendi o que impede:

Pra um api do festival existir, só preciso saber quais os dados que você quer puxar.

Pra você "consumir" os dados da api, só precisa de uma biblioteca REST (e aparentemente, como você programa em PHP, eu recomendaria a https://github.com/Respect/Rest do @alganet (que é um cara bem foda em PHP :) - mas não sei se ela consome.

Como funcionaria: 

1 - Você faz um requisição GET pra festival.org.br/ideia/1 e recebe no output um JSON.
2 - Você faz parse dessa informação e salva no banco da sua app. (file_get_contents? curl? Rest?)
3 - Monta o mapa de vista.

Como eu disse, é simples se soubermos quais os dados que queremos extrair. O resto do trabalho é só consumir a API.
Usar API é muito mais inteligente pois assim podemos ter todo um ecossistema de aplicações em torno das ideias. Imagine quantas apps dá pra se montar só consumindo a API. :-)

Aí fica a pergunta, quais dados?

**Comment by luizfonseca** [comment]
Outra lib http://guzzlephp.org/tour/http.html

**Comment by luizfonseca** [comment]
E um exemplo que o @alganet enviou, usando o `stream_context_create`: http://codepad.org/f2wqXfA1

Penso em trabalhar com a API de forma pública - sendo assim só GET será necessário. :-)

**Comment by alganet** [comment]
Com GET é ainda mais simples:

```
$response = file_get_contents('http://example.com/apiendpoint/?foo=bar');
```

O `stream_context_create` é só pra mexer com métodos e headers diferentes.

**Comment by danielweinmann** [comment]
Gente, tô fechando este issue aqui, pois estamos desenvolvendo uma integração direto com o Google Maps, para mostrar um mapa das ideias.

Queríamos muito usar o Mapas de Vista, pra fomentar a comunidade, mas a integração Wordpress <-> Rails é bem complicada, e já temos muito código pronto em Rails pra integrar com o Google Maps.

De todas as formas, o objetivo de ter o mapa das ideias tá no forno e logo vamos ter o mapa ;)
