### ISSUE TITLE
[Tokbox][OpenTok] Instructions in how to use the API 

### ISSUE THREAD

**Issue by luizfonseca** [engageis/festivaldeideias#14]
Adicionar uma explicação melhor na wiki do Projeto sobre como usar a sala de cocriação.

Ver commit 1c3f11fa4b0003488c6a437cef4717af2e682bee

**Comment by chicolismo** [comment]
Luiz, não estou mais no Festival, nem tenho acesso ao projeto no Pivotal
Tracker. Confesso que não tenho muita ideia do que está acontecendo
atualmente no projeto.

2012/6/5 Luiz Fonseca <
reply@reply.github.com

> Adicionar uma explicação melhor na wiki do Projeto sobre como usar a sala
> de cocriação.
> 
> Ver commit 1c3f11fa4b0003488c6a437cef4717af2e682bee
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/softa/festivaldeideias/issues/14

## 

_Carlos F. Pinheiro_

**Comment by danielweinmann** [comment]
Man, I'm closing this issue until (and if) we decide to keep focusing on the cocriation room ;) for now, I think we can solemnly ignore it, since nobody is using it.
