### ISSUE TITLE
[Bug] Search is not working in production

### ISSUE THREAD

**Issue by luizfonseca** [engageis/festivaldeideias#24]
Due to postgres version on heroku, search with associated model is not possible yet.

**Comment by danielweinmann** [comment]
@runeroniek, did you upgrade our database yet?

**Comment by luizfonseca** [comment]
Yep, since Aug 1st. We have the development plan with 14k rows of limit and we're currently using 7k rows.

> > http://legacydbs.herokuapp.com/

**Comment by danielweinmann** [comment]
Great! I'll make this search work, then ;)
