### ISSUE TITLE
Travis is getting Firefox problem

### ISSUE THREAD

**Issue by danielweinmann** [engageis/festivaldeideias#30]
I have no idea why this is happening, but we are not being able tu run the cucumber features that use the browser on Travis.

**Comment by danielweinmann** [comment]
@runeroniek, can you check this one?

**Comment by luizfonseca** [comment]
On my way!

**Comment by danielweinmann** [comment]
@runeroniek, any news about this?

**Comment by luizfonseca** [comment]
Fixed. But 3 rspec tests are failing. I'm closing this issue.
