### ISSUE TITLE
Even though we have a badge upload on the admin, the badges for the categories are hard coded

### ISSUE THREAD

**Issue by danielweinmann** [engageis/festivaldeideias#40]

**Comment by gustavoguichard** [comment]
I thought that the badge upload was working

**Comment by danielweinmann** [comment]
Man, don't worry with this issue right now. We're not gonna need to add/change categories so soon ;)

But the problem is not in the upload, but is because we have IdeaCategory#badge hard coding the images. Just for the record.

**Comment by danielweinmann** [comment]
Gustavo,

They are adding new categories right now. Can you work on this issue?
